#include "logger.h"

void test_create_table(void);
void test_drop_table(void);
void test_create_table_with_foreign_key(void);
void test_create_table_multiple_columns(void);
void test_create_table_new_types(void);
void test_foreign_key_validation(void);
void test_foreign_key_self_reference(void);
void test_foreign_key_multiple_references(void);

void test_insert_single_row(void);
void test_insert_multiple_values(void);
void test_insert_mixed_types(void);
void test_insert_with_column_names(void);
void test_insert_select_new_types(void);
void test_update_single_row(void);
void test_update_multiple_rows(void);
void test_update_all_rows(void);
void test_delete_single_row(void);
void test_delete_multiple_rows(void);
void test_delete_all_rows(void);
void test_insert_with_comments(void);
void test_multiple_statements(void);
void test_update_with_expression(void);
void test_update_multiple_columns(void);
void test_update_no_match(void);
void test_delete_with_and_or(void);
void test_insert_empty_values(void);
void test_insert_string_with_spaces(void);
void test_update_same_value(void);

void test_select_all(void);
void test_select_columns(void);
void test_select_with_where(void);
void test_select_with_and_or(void);
void test_select_with_like(void);
void test_select_with_order_by(void);
void test_select_with_limit(void);
void test_select_with_order_by_limit(void);
void test_select_distinct(void);
void test_select_is_null(void);
void test_select_case_sensitivity(void);
void test_select_with_not_equal(void);
void test_select_with_in_clause(void);
void test_select_with_not_like(void);
void test_select_with_multiple_conditions(void);
void test_select_empty_result(void);
void test_select_all_columns(void);
void test_select_with_parentheses(void);
void test_select_is_not_null(void);

void test_count_aggregate(void);
void test_sum_aggregate(void);
void test_avg_aggregate(void);
void test_min_aggregate(void);
void test_max_aggregate(void);
void test_multiple_aggregates(void);
void test_aggregate_with_where(void);
void test_aggregate_edge_cases(void);
void test_count_all_vs_column(void);
void test_aggregate_with_all_types(void);
void test_aggregate_large_dataset(void);
void test_aggregate_with_zero_values(void);
void test_aggregate_with_like_where(void);
void test_aggregate_multiple_wheres(void);
void test_aggregate_with_order_by_limit(void);

void test_string_copy(void);

void test_string_functions(void);
void test_numeric_functions(void);
void test_concat_function(void);
void test_substring_function(void);
void test_length_function(void);
void test_mod_function(void);
void test_power_function(void);
void test_mid_function(void);
void test_scalar_in_expressions(void);

void test_inner_join(void);
void test_left_join(void);
void test_join_multiple_matches(void);
void test_join_no_matches(void);
void test_join_empty_table(void);
void test_join_syntax_variations(void);
void test_self_join(void);
void test_three_table_join(void);

void test_create_index(void);
void test_create_multiple_indexes(void);
void test_index_on_string_column(void);
void test_drop_index(void);
void test_index_filter_equality(void);
void test_index_filter_with_large_table(void);
void test_hash_join_inner(void);
void test_hash_join_left(void);
void test_hash_join_large_tables(void);
void test_hash_join_multiple_matches(void);
void test_hash_join_no_matches(void);
void test_index_with_string_equality(void);
void test_index_rebuild(void);
void test_complex_join_with_index(void);

void test_subquery_with_comparison(void);
void test_correlated_subquery(void);
void test_subquery_in_insert(void);
void test_subquery_with_aggregates(void);
void test_exists_subquery(void);
void test_nested_subquery(void);
void test_subquery_with_join(void);
void test_scalar_subquery(void);
void test_btree_basic(void);
void test_query_stats_basic(void);
void test_aggregation_improved(void);
void test_new_features_simple(void);
void test_btree_basic(void);
void test_query_stats_basic(void);
void test_aggregation_improved(void);

int main(void) {
    set_log_level(LOG_DEBUG);
    log_msg(LOG_INFO, "========================================");
    log_msg(LOG_INFO, "Running Tests...");
    log_msg(LOG_INFO, "========================================");

    log_msg(LOG_INFO, "\n=== DDL Tests ===");
    test_create_table();
    test_drop_table();
    test_create_table_with_foreign_key();
    test_create_table_multiple_columns();
    test_create_table_new_types();
    test_foreign_key_validation();
    test_foreign_key_self_reference();
    test_foreign_key_multiple_references();

    log_msg(LOG_INFO, "\n=== DML Tests ===");
    test_insert_single_row();
    test_insert_multiple_values();
    test_insert_mixed_types();
    test_insert_with_column_names();
    test_insert_select_new_types();
    test_update_single_row();
    test_update_multiple_rows();
    test_update_all_rows();
    test_delete_single_row();
    test_delete_multiple_rows();
    test_delete_all_rows();
    test_insert_with_comments();
    test_multiple_statements();
    test_update_with_expression();
    test_update_multiple_columns();
    test_update_no_match();
    test_delete_with_and_or();
    test_insert_empty_values();
    test_insert_string_with_spaces();
    test_update_same_value();

    log_msg(LOG_INFO, "\n=== SELECT Tests ===");
    test_select_all();
    test_select_columns();
    test_select_with_where();
    test_select_with_and_or();
    test_select_with_like();
    test_select_with_order_by();
    test_select_with_limit();
    test_select_with_order_by_limit();
    test_select_distinct();
    test_select_is_null();
    test_select_case_sensitivity();
    test_select_with_not_equal();
    test_select_with_in_clause();
    test_select_with_not_like();
    test_select_with_multiple_conditions();
    test_select_empty_result();
    test_select_all_columns();
    test_select_with_parentheses();
    test_select_is_not_null();

    log_msg(LOG_INFO, "All SELECT tests passed successfully!");
    log_msg(LOG_INFO, "========================================");
    log_msg(LOG_INFO, "\n=== Aggregate Tests ===");
    test_count_aggregate();
    test_sum_aggregate();
    test_avg_aggregate();
    test_min_aggregate();
    test_max_aggregate();
    test_multiple_aggregates();
    test_aggregate_with_where();
    test_aggregate_edge_cases();
    test_count_all_vs_column();
    test_aggregate_with_all_types();
    test_aggregate_large_dataset();
    test_aggregate_with_zero_values();
    test_aggregate_with_like_where();
    test_aggregate_multiple_wheres();
    test_aggregate_with_order_by_limit();
    log_msg(LOG_INFO, "All aggregate tests passed successfully!");
    log_msg(LOG_INFO, "========================================");
    log_msg(LOG_INFO, "\n=== Utility Tests ===");
    test_string_copy();
    log_msg(LOG_INFO, "Utility tests passed!");
    log_msg(LOG_INFO, "========================================");
    log_msg(LOG_INFO, "\n=== Index Tests ===");
    test_create_index();
    test_index_filter_equality();
    log_msg(LOG_INFO, "Index tests passed!");
    log_msg(LOG_INFO, "========================================");
    log_msg(LOG_INFO, "All tests passed!");
    log_msg(LOG_INFO, "========================================");

    return 0;
}
